# Generated by Django 6.1 on 2026-08-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo Profissional')),
                ('competencias', models.TextField(blank=True, null=True, verbose_name='Competências')),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades')),
                ('formacao', models.CharField(choices=[('fundamental_completo', 'Fundamental Completo'), ('fundamental_incompleto', 'Fundamental Incompleto'), ('medio_completo', 'Médio Completo'), ('medio_incompleto', 'Médio Incompleto'), ('superior_completo', 'Superior Completo'), ('superior_incompleto', 'Superior Incompleto')], max_length=30, verbose_name='Tipo de Formação')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do curso')),
                ('descricao', models.TextField(verbose_name='Descrição do curso')),
                ('carga_horaria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carga horária')),
                ('link_inscricao', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link de acesso/inscrição')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_post', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicado', 'Publicado')], default='Rascunho', max_length=20, verbose_name='Status de Exibição')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome/Título do Feedback')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição geral')),
                ('pontos_positivos', models.TextField(blank=True, null=True, verbose_name='Pontos Positivos')),
                ('pontos_negativos', models.TextField(blank=True, null=True, verbose_name='Pontos Negativos')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Diplomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título / Nome do Certificado')),
                ('arquivo', models.FileField(upload_to='diplomas/', verbose_name='Arquivo (PDF/Imagem)')),
                ('data_upload', models.DateField(auto_now_add=True, verbose_name='Data de envio')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='app.curriculos', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Diploma/Certificado',
                'verbose_name_plural': 'Diplomas/Certificados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone para contato')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('site', models.URLField(blank=True, null=True, verbose_name='URL do site')),
                ('verificada', models.BooleanField(default=False)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empresas/', verbose_name='Imagem da empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome social e/ou de registro da pessoa')),
                ('genero', models.CharField(blank=True, max_length=25, null=True, verbose_name='Identidade de gênero')),
                ('pronomes', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pronomes')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.AddField(
            model_name='curriculos',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculo', to='app.pessoas', verbose_name='Pessoa'),
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL do site da vaga/curso proposto')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('tipo', models.CharField(choices=[('Curso', 'Curso'), ('Vaga', 'Vaga')], max_length=20, verbose_name='Tipo de Sugestão')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='app.pessoas', verbose_name='Candidato(a)')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da vaga')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('salario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salário')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Deferida', 'Deferida / Publicada'), ('Indeferida', 'Indeferida')], default='Pendente', max_length=20, verbose_name='Status de Aprovação (Admin)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app.empresas', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.cursos', verbose_name='Curso')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.vagas', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='InscricoesCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('status_curso', models.CharField(choices=[('Cursando', 'Cursando / Em andamento'), ('Concluido', 'Concluído')], default='Cursando', max_length=30, verbose_name='Status do Curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_cursos', to='app.cursos', verbose_name='Curso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_cursos', to='app.pessoas', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Inscrição em Curso',
                'verbose_name_plural': 'Inscrições em Cursos',
                'unique_together': {('pessoa', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Candidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('status_vaga', models.CharField(choices=[('Pendente', 'Pendente / Em análise'), ('Deferida', 'Deferida'), ('Indeferida', 'Indeferida')], default='Pendente', max_length=30, verbose_name='Status da Candidatura')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='app.pessoas', verbose_name='Candidato(a)')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='app.vagas', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'unique_together': {('pessoa', 'vaga')},
            },
        ),
    ]
