# Generated by Django 6.1 on 2026-08-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestoes',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='app.pessoas', verbose_name='Pessoa'),
        ),
    ]
