# Generated by Django 6.1 on 2026-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sugestoes_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='salario',
            field=models.FloatField(blank=True, null=True, verbose_name='Salário'),
        ),
    ]
