# Generated by Django 6.1 on 2026-08-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vagas_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
